In [1]:
import numpy as np

In [2]:
mya = np.array([[1,2,3,84,5]], np.int8)

In [3]:
mya[0,1]

2

In [4]:
mya.shape

(1, 5)

In [5]:
mya.dtype

dtype('int8')

In [6]:
mya[0,1] = 33

In [7]:
mya

array([[ 1, 33,  3, 84,  5]], dtype=int8)

In [8]:
listarray =np.array([[1,2,3], [4,5,6], [7,8,9]])

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
listarray.dtype


dtype('int32')

In [11]:
listarray.shape


(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({23,33,23})

array({33, 23}, dtype=object)

In [14]:
zeros = np.zeros((2,3))

In [15]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
zeros.size

6

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lsp = np.linspace(1,5,5)

In [20]:
lsp

array([1., 2., 3., 4., 5.])

In [21]:
emp = np.empty((3,4))

In [22]:
emp

array([[1.25793676e-311, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 2.46567317e+179, 5.20268094e-090,
        5.64349391e-038],
       [1.52394232e-052, 4.00868547e+174, 6.48224659e+170,
        4.93432906e+257]])

In [23]:
emp_like = np.empty_like(lsp)

In [24]:
emp_like

array([1., 2., 3., 4., 5.])

In [25]:
ide = np.identity(33)

In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
ide.shape

(33, 33)

In [28]:
ar = np.arange(99)

In [29]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
ar = ar.reshape(3,33)

In [35]:
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])